Subjects/Glimpse-master/source/Glimpse.Mvc3.MusicStore.Sample/Controllers/FileUploadController.cs
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class FileUploadController : Controller
    {
        public ActionResult Index(string fileName = "")
        {
            ViewBag.FileName = fileName;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file)
        {
            try
            {
                byte[] input = new byte[file.ContentLength];
                file.InputStream.Read(input, 0, file.ContentLength);

                return RedirectToAction("Index", new { fileName = file.FileName });
            }
            catch
            {
                return View();
            }
        }
    }
}

Subjects/Glimpse-master/source/Glimpse.Mvc3.MusicStore.Sample/Views/FileUpload/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

<fieldset>

        <input type="file" name="file" id="file" />
        <input type="submit" value="Create" />
    
    </fieldset>
}

Subjects/Glimpse-master/source/Glimpse.Mvc3.MusicStore.Sample/Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Upload a test file</h2>

@if (!string.IsNullOrEmpty(ViewBag.FileName))
{
    <span>File Uploaded: @ViewBag.FileName</span>
    <br/>
}

@Html.ActionLink("Upload File", "Create")